# -*- mode: ruby -*-
# vi: set ft=ruby :

# Tạo máy ảo từ box centos/7, gán địa chỉ IP, đặt hostname, gán 2GB bộ nhớ, 2 cpus  
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "private_network", ip: "172.16.11.101"
    config.vm.hostname = "ubuntu.xtl"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "ubuntu.xtl"
       vb.cpus = 2
       vb.memory = "2048"
    end
    
    # Chạy file install-docker-kube.sh sau khi nạp Box
    config.vm.provision "shell", path: "./../install-ubuntu.sh"
  
    # Chạy các lệnh shell
    config.vm.provision "shell", inline: <<-SHELL
      # Đặt pass 123 có tài khoản root và cho phép SSH
      echo -e "123\n123" | passwd root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      # apt-get install systemd -y
      systemctl restart ssh
  
    SHELL
  end
  